name: Jira Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Normalize ref
        id: normalized
        run: |
          REF=${GITHUB_REF#refs/heads/}
          echo "ref=$REF" >> $GITHUB_OUTPUT

      - name: Extract Jira issue key from branch name
        id: extract
        run: |
          echo "Branch name: ${{ steps.normalized.outputs.ref }}"
          ISSUE_KEY=$(echo "${{ steps.normalized.outputs.ref }}" | grep -oE '[A-Z]+-[0-9]+' || true)
          echo "Extracted Jira issue key: $ISSUE_KEY"
          echo "jira_key=$ISSUE_KEY" >> $GITHUB_OUTPUT

      - name: Create GitHub Deployment
        id: create_deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          ref: ${{ steps.normalized.outputs.ref }}

      - name: Update Deployment Status to Success
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment-id: ${{ steps.create_deployment.outputs.deployment_id }}
          state: success
          environment: production
